# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to test environment

on:
  workflow_dispatch:
  push:
    branches: ["development"]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run build:mta --if-present
      - uses: MindsetConsulting/sap-btp-action@master
        with:
          cf_api: https://api.cf.us10-001.hana.ondemand.com
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: tdd-mindsetdevelopment
          cf_space: dev-1
          cf_origin: a16243838-platform
          command: deploy mta_archives/assetwise_pg_db_1.0.0.mtar -f
